### ISSUE TITLE
Need help to configure peer server

### ISSUE THREAD

**Issue by Siva-Coder** [metehankurucu/react-native-video-calling-app#2]
export const PEER_SERVER_HOST = '';
export const PEER_SERVER_PORT = '';
export const PEER_SERVER_PATH = '';
export const SERVER_URL = '';

Can you please let me know that how can I configure PEER_SERVER_HOST, PEER_SERVER_PORT, and PEER_SERVER_PATH?

I've successfully hosted socket server and given socket server address to SERVER_URL;

**Comment by metehankurucu** [comment]
PEER_SERVER_HOST is address of peer server, for example your local ip 192.168.1.101
PEER_SERVER_PORT is port of server you specified here https://github.com/metehankurucu/peer-api/blob/main/peer-server/server.js#L19
PEER_SERVER_PATH  is path of server you specified here https://github.com/metehankurucu/peer-api/blob/main/peer-server/server.js#L14

**Comment by Siva-Coder** [comment]
Thank you very much!

For example, if I hosted the peer server in Heroku or AWS (live) and not in my localhost then what will be that PEER_SERVER_HOST.

Thanks
