### ISSUE TITLE
when i run "node ./bin/www" inside of socket-server folder i got error No default engine was specified and no extension was provided.

### ISSUE THREAD

**Issue by rameshjega** [metehankurucu/react-native-video-calling-app#4]
when i run "node ./bin/www" inside of socket-server folder i got this error
![error1](https://user-images.githubusercontent.com/52094962/129734385-e8dc98d5-a6d3-496f-a710-b484489b7181.png)

**Comment by metehankurucu** [comment]
repo updated. you can see it and open issue related server here https://github.com/metehankurucu/peer-api

**Comment by rameshjega** [comment]
![err](https://user-images.githubusercontent.com/52094962/130779124-5e7269c8-84cf-48d6-b0fb-c631fe70125c.png)
![errrrrrrrrr](https://user-images.githubusercontent.com/52094962/130779314-d2204c8d-3431-43b0-97b6-aa8190486580.png)

still now its not working

i am start node server.js from peer-server
and npm run dev from socket-server 


but i have  Peer server error [Error: Could not get an ID from the server.]
